POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Tutorial Node",
    "description": "Este é o primeiro video de Node.js",
    "duration": 180
}
###

GET http://localhost:3000/videos?search=node
# GET http://localhost:3000/videos

###

PUT http://localhost:3000/videos/37c90993-1b62-4113-9c7d-e8e953906ee2
Content-Type: application/json

{
    "title": "Auterei este video",
    "description": "descrição atualizada",
    "duration": 345
}

###

DELETE  http://localhost:3000/videos/07b597f8-4139-497d-8205-139f0075daa1




